apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  workflow_dispatch:
jobs:
  build:
    steps:
      - name: Install dependencies
        uses: docker://node:18-alpine
        shell: sh
        run: |
          npm install

      - name: Run tests
        uses: docker://node:18-alpine
        shell: sh
        run: |
          npm test