apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  workflow_dispatch:
jobs:
  build:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          start=$(date +%s)
          end=$((start + 300))
          while [ $(date +%s) -lt $end ]; do
            elapsed=$(($(date +%s) - start))
            echo "[$(date '+%H:%M:%S')] Running step $((elapsed / 10))... (${elapsed}s elapsed)"
            sleep 2
          done
          echo "Workflow complete after 5 minutes"
