apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  workflow_dispatch:
jobs:
  build:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          end=$((SECONDS + 300))
          while [ $SECONDS -lt $end ]; do
            echo "[$(date '+%H:%M:%S')] Running step $((SECONDS / 10))..."
            sleep 2
          done
          echo "Workflow complete after 5 minutes"
